In [12]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import \
preprocess_input, decode_predictions
import numpy as np

In [13]:
# Instancia o modelo pré-treinado ResNet50 
modelo = ResNet50(weights='imagenet')

In [14]:
path = 'E:/FIC_DL/imagens/'

# Usa uma imagem qualquer, redimensionando para a configuração de entrada da ResNet50
img = image.load_img(path + '_form.jpg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

#imagem_teste.jpg, _strange2.jpg, _form.jpg, ele_.jpg, on_.jpg, tuc_.png

In [15]:
x

array([[[[ 90.061  , 112.221  , 108.32   ],
         [ 89.061  , 109.221  , 105.32   ],
         [ 92.061  , 112.221  , 108.32   ],
         ...,
         [ 98.061  , 107.221  , 105.32   ],
         [ 98.061  , 107.221  , 105.32   ],
         [103.061  , 112.221  , 110.32   ]],

        [[ 81.061  , 103.221  ,  99.32   ],
         [ 81.061  , 101.221  ,  97.32   ],
         [ 84.061  , 104.221  , 100.32   ],
         ...,
         [ 93.061  , 102.221  , 100.32   ],
         [ 93.061  , 102.221  , 100.32   ],
         [ 97.061  , 106.221  , 104.32   ]],

        [[ 81.061  , 103.221  ,  99.32   ],
         [ 78.061  , 100.221  ,  96.32   ],
         [ 81.061  , 103.221  ,  99.32   ],
         ...,
         [ 89.061  ,  98.221  ,  96.32   ],
         [ 89.061  ,  98.221  ,  96.32   ],
         [ 96.061  , 105.221  , 103.32   ]],

        ...,

        [[139.061  , 121.221  , 113.32   ],
         [134.061  , 116.221  , 108.32   ],
         [132.061  , 114.221  , 106.32   ],
         ...,


Faz a predição feita pelo modelo pré-treinado da classe da imagem escolhida

In [21]:
preds = modelo.predict(x)
print('Predição:', decode_predictions(preds, top=5)[0])

1/1 [==============================] - 0s 132ms/step
Predição: [('n02219486', 'ant', 0.999998), ('n01774384', 'black_widow', 1.1444974e-06), ('n01773549', 'barn_spider', 2.536994e-07), ('n02167151', 'ground_beetle', 1.9866506e-07), ('n03530642', 'honeycomb', 1.7552675e-07)]


In [17]:
for i, layer in enumerate(modelo.layers):
   print(i, layer.name)

0 input_2
1 conv1_pad
2 conv1_conv
3 conv1_bn
4 conv1_relu
5 pool1_pad
6 pool1_pool
7 conv2_block1_1_conv
8 conv2_block1_1_bn
9 conv2_block1_1_relu
10 conv2_block1_2_conv
11 conv2_block1_2_bn
12 conv2_block1_2_relu
13 conv2_block1_0_conv
14 conv2_block1_3_conv
15 conv2_block1_0_bn
16 conv2_block1_3_bn
17 conv2_block1_add
18 conv2_block1_out
19 conv2_block2_1_conv
20 conv2_block2_1_bn
21 conv2_block2_1_relu
22 conv2_block2_2_conv
23 conv2_block2_2_bn
24 conv2_block2_2_relu
25 conv2_block2_3_conv
26 conv2_block2_3_bn
27 conv2_block2_add
28 conv2_block2_out
29 conv2_block3_1_conv
30 conv2_block3_1_bn
31 conv2_block3_1_relu
32 conv2_block3_2_conv
33 conv2_block3_2_bn
34 conv2_block3_2_relu
35 conv2_block3_3_conv
36 conv2_block3_3_bn
37 conv2_block3_add
38 conv2_block3_out
39 conv3_block1_1_conv
40 conv3_block1_1_bn
41 conv3_block1_1_relu
42 conv3_block1_2_conv
43 conv3_block1_2_bn
44 conv3_block1_2_relu
45 conv3_block1_0_conv
46 conv3_block1_3_conv
47 conv3_block1_0_bn
48 conv3_block1_3_bn

### Pytorch

In [26]:
import torch
import torchvision.transforms as transforms
from torchvision import models
import numpy as np
from PIL import Image

In [29]:
# Uso do modelo pré-treinado da RESNET
modelo = models.resnet50(weights=True)

Aplicação de Data augmentation e normalização com uso das configurações de média e desvio padrão da RESNET

In [30]:
path = 'E:/FIC_DL/imagens/'

transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [32]:
#  Carrega uma imagem e pre-processa para o modelo da RESNET50 
img = Image.open(path + 'arara.jpg')
img = transform(img)
x = img.unsqueeze(0)

In [33]:
# Realiza a predição da classe usando o modelo pré-treinado com as top-3 probabilidades
modelo.eval()
with torch.no_grad():
    preds = modelo(x)
probs = torch.nn.functional.softmax(preds, dim=1)
top_probs, top_idxs = torch.topk(probs, k=3)
print('Predicted:', top_idxs, top_probs)

Predicted: tensor([[88, 87, 90]]) tensor([[9.9970e-01, 1.2698e-04, 1.0411e-04]])


In [34]:
import urllib.request

In [35]:
# Download dos arquivos de rótulos da imagenet 
url = "https://raw.githubusercontent.com/pytorch/hub/\
master/imagenet_classes.txt"
urllib.request.urlretrieve(url, "imagenet_classes.txt")

('imagenet_classes.txt', <http.client.HTTPMessage at 0x1eadc0f58d0>)

In [36]:
import torch
from torchvision import models, transforms

In [119]:
# Carrega o modelo pré-treinado da ResNet50
model = models.resnet50(pretrained=True)

In [120]:
# Configura o modelo para modo de validação 
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [121]:
# Configura as transformações de preprocessamento da imagem 
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], 
                         std=[0.229, 0.224, 0.225])
])

In [198]:
# Carrega uma imagem e preprocessa para o modelo da ResNet50
path = 'E:/FIC_DL/imagens/'
img = Image.open(path + '_dc.jpg')
img_tensor = transform(img)
img_tensor = img_tensor.unsqueeze(0) # Adiciona  batch dimension

In [199]:
# Usa o modelo pré-treinado para predizer a classe da imagem
with torch.no_grad():
    preds = model(img_tensor)

In [200]:
probs = torch.nn.functional.softmax(preds, dim=1)
top_k_probs, top_k_indices = torch.topk(probs, k=5)

In [201]:
top_k_probs, top_k_indices

(tensor([[0.2050, 0.0925, 0.0705, 0.0443, 0.0343]]),
 tensor([[281, 904, 285, 282, 207]]))

In [202]:
# Carrega os rótulos das classes da ImageNet
with open('imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [203]:
#print(labels)

In [204]:
# Mostra as predições top-k com os rótulos das predições
for i in range(len(top_k_probs[0])):
    print(f"{labels[top_k_indices[0][i]]}:\
    {top_k_probs[0][i].item():.4f}")

tabby:    0.2050
window screen:    0.0925
Egyptian cat:    0.0705
tiger cat:    0.0443
golden retriever:    0.0343


In [100]:
import torch
from torchvision import models, transforms

# Carrega o modelo pré-treinado da ResNet50
model = models.resnet50(pretrained=True)

# Configura o modelo para modo de validação 
model.eval()

# Configura as transformações de preprocessamento da imagem 
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Carrega uma imagem e preprocess para o modelo da ResNet50
path = 'E:/FIC_DL/imagens/'
img = Image.open(path + 'tucano3.png')
img_tensor = transform(img)
img_tensor = img_tensor.unsqueeze(0) # Adiciona  Add batch dimension
#img_tensor = img_tensor.to(device='cuda') # Move tensor to GPU if available

# Usa o modelo pré-treinado para predizer a classe da imagem
with torch.no_grad():
    preds = model(img_tensor)

print(top_k_probs, top_k_indices)

# Converte os logits das probabilidades e extrai as top k predições
probs = torch.nn.functional.softmax(preds, dim=1)
top_k_probs, top_k_indices = torch.topk(probs, k=5)

# Carrega os rótulos das classes da ImageNet
with open('imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

# Mostra as predições top-k com os rótulos das predições
for i in range(len(top_k_probs[0])):
    print(f"{labels[top_k_indices[0][i]]}: {top_k_probs[0][i].item():.4f}")


tensor([[9.9595e-01, 4.0333e-03, 4.2964e-06, 2.6416e-06, 1.9082e-06]]) tensor([[ 96,  93,  88, 145,  84]])
toucan: 0.9960
hornbill: 0.0040
macaw: 0.0000
king penguin: 0.0000
peacock: 0.0000
