In [1]:
v_txt = input('Entre com o texto: ')

Entre com o texto: Davi Brenno Calheiro Souza


In [4]:
v_txt[3:]

'i Brenno Calheiro Souza'

In [5]:
v_txt[2:]

'vi Brenno Calheiro Souza'

In [6]:
v_txt[4:5]

' '

In [7]:
v_txt[::2]

'Dv rnoCler oz'

In [8]:
v_txt[::-1]

'azuoS oriehlaC onnerB ivaD'

In [9]:
v_lst1 = ['Banana', 10]

In [10]:
v_lst2 = ['Laranja', 15]

In [11]:
v_lst3 = ['Melancia', 40]

In [12]:
v_lst4 = ['Manga', 10]

In [13]:
v_lst5 = ['Uva', 35]

In [14]:
v_frutas = [v_lst1, v_lst2, v_lst3, v_lst4, v_lst5]

In [15]:
v_frutas

[['Banana', 10], ['Laranja', 15], ['Melancia', 40], ['Manga', 10], ['Uva', 35]]

In [17]:
v_frutas[1]

['Laranja', 15]

In [18]:
v_frutas[1][0]

'Laranja'

In [19]:
v_frutas[1][0][5]

'j'

In [21]:
for frutas in v_frutas:
    print(frutas)

['Banana', 10]
['Laranja', 15]
['Melancia', 40]
['Manga', 10]
['Uva', 35]


In [22]:
len(v_frutas)

5

In [32]:
v_total = 0

for frutas in v_frutas:
    v_total += frutas[1] 
print(v_total)

110


In [55]:
for fruta in v_frutas:
    print('')
    for letra in fruta[0]:
        print(letra)


B
a
n
a
n
a

L
a
r
a
n
j
a

M
e
l
a
n
c
i
a

M
a
n
g
a

U
v
a


In [54]:
for fruta in v_frutas:
    print('')
    print(fruta[0])
    for letra in fruta[0]:
        print(letra)


Banana
B
a
n
a
n
a

Laranja
L
a
r
a
n
j
a

Melancia
M
e
l
a
n
c
i
a

Manga
M
a
n
g
a

Uva
U
v
a


In [56]:
v_frutas

[['Banana', 10], ['Laranja', 15], ['Melancia', 40], ['Manga', 10], ['Uva', 35]]

In [57]:
v_frutas.append(['Kiwi', 20])

In [58]:
v_frutas

[['Banana', 10],
 ['Laranja', 15],
 ['Melancia', 40],
 ['Manga', 10],
 ['Uva', 35],
 ['Kiwi', 20]]

In [59]:
v_frutas.insert(0, ['Abacaxi', 30])

In [60]:
v_frutas

[['Abacaxi', 30],
 ['Banana', 10],
 ['Laranja', 15],
 ['Melancia', 40],
 ['Manga', 10],
 ['Uva', 35],
 ['Kiwi', 20]]

In [61]:
v_frutas.insert(1, ['Kiwi', 20])

In [62]:
v_frutas

[['Abacaxi', 30],
 ['Kiwi', 20],
 ['Banana', 10],
 ['Laranja', 15],
 ['Melancia', 40],
 ['Manga', 10],
 ['Uva', 35],
 ['Kiwi', 20]]

In [63]:
v_frutas.remove(['Kiwi', 20])

In [64]:
v_frutas

[['Abacaxi', 30],
 ['Banana', 10],
 ['Laranja', 15],
 ['Melancia', 40],
 ['Manga', 10],
 ['Uva', 35],
 ['Kiwi', 20]]

In [65]:
v_frutas.pop()

['Kiwi', 20]

In [66]:
v_frutas

[['Abacaxi', 30],
 ['Banana', 10],
 ['Laranja', 15],
 ['Melancia', 40],
 ['Manga', 10],
 ['Uva', 35]]

In [67]:
v_frutas.pop(2)

['Laranja', 15]

In [68]:
v_frutas

[['Abacaxi', 30], ['Banana', 10], ['Melancia', 40], ['Manga', 10], ['Uva', 35]]

In [72]:
#Comentário
v_frutas.pop() #comentário

['Uva', 35]

# 4ª Aula - TETI - Desempacotamento

In [74]:
v_compra1, * v_resto = v_frutas

In [75]:
v_compra1

['Abacaxi', 30]

In [76]:
v_resto

[['Banana', 10], ['Melancia', 40], ['Manga', 10]]

In [77]:
v_frutas

[['Abacaxi', 30], ['Banana', 10], ['Melancia', 40], ['Manga', 10]]

In [78]:
'Davi Brenno Calheiro Souza'.split()

['Davi', 'Brenno', 'Calheiro', 'Souza']

In [79]:
prim_nome, *meio, sobrenome = 'Davi Brenno Calheiro Souza'.split()

In [80]:
prim_nome

'Davi'

In [81]:
meio

['Brenno', 'Calheiro']

In [82]:
sobrenome

'Souza'

In [83]:
v_t1 = 1, 2, 3, 4, 5

In [84]:
v_t1

(1, 2, 3, 4, 5)

In [85]:
type(v_t1)

tuple

# 4ª Aula - TETI - Dicionários(Dic)

In [86]:
dic1 = dict({"cod": 2123, "descricao": "Notebook Dell", "preco": 4000}) #Dicionário literal
dic2 = dict(cod=2123, descricao="Notebook Dell", preco=4000) # Argumentos palavras-chave
dic3 = dict([("cod", 2123), ("descricao", "Notebook Dell"), ("preco", 4000)])  #Sequência
dic4 = {"cod": 2123, "descricao": "Notebook Dell", "preco": 4000 } #Dicionário literal

In [87]:
dic1

{'cod': 2123, 'descricao': 'Notebook Dell', 'preco': 4000}

In [88]:
dic2

{'cod': 2123, 'descricao': 'Notebook Dell', 'preco': 4000}

In [89]:
dic3

{'cod': 2123, 'descricao': 'Notebook Dell', 'preco': 4000}

In [90]:
dic4

{'cod': 2123, 'descricao': 'Notebook Dell', 'preco': 4000}

In [91]:
dic1['descricao']

'Notebook Dell'

In [92]:
dic2.keys()

dict_keys(['cod', 'descricao', 'preco'])

In [93]:
dic2.values()

dict_values([2123, 'Notebook Dell', 4000])

In [94]:
list(dic2.keys())

['cod', 'descricao', 'preco']

In [95]:
list(dic2.values())

[2123, 'Notebook Dell', 4000]

In [96]:
for chave in dic2:
    print(chave + ' ' + str(dic2[chave]))

cod 2123
descricao Notebook Dell
preco 4000


In [98]:
for texto in dic2:
    print(texto + ' ' + str(dic2[texto]))

cod 2123
descricao Notebook Dell
preco 4000


In [1]:
dic1 = {}.fromkeys('ABCDEFGHIJKLMNOPQRSTUVWXYZ', 10)

In [2]:
dic1

{'A': 10,
 'B': 10,
 'C': 10,
 'D': 10,
 'E': 10,
 'F': 10,
 'G': 10,
 'H': 10,
 'I': 10,
 'J': 10,
 'K': 10,
 'L': 10,
 'M': 10,
 'N': 10,
 'O': 10,
 'P': 10,
 'Q': 10,
 'R': 10,
 'S': 10,
 'T': 10,
 'U': 10,
 'V': 10,
 'W': 10,
 'X': 10,
 'Y': 10,
 'Z': 10}

In [7]:
s1 = set('KMWXYÇ')

In [8]:
s1

{'K', 'M', 'W', 'X', 'Y', 'Ç'}

In [9]:
achou = dic1.keys() & s1

In [10]:
achou

{'K', 'M', 'W', 'X', 'Y'}

In [11]:
dic1.keys() - s1

{'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'L',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'Z'}

In [12]:
s1 - dic1.keys()

{'Ç'}

In [13]:
dic1.keys() | s1

{'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'Ç'}

In [14]:
antonimos = {"quente": "frio", "alto": "baixo", "certo":"errado", "bonito":"feio", 
             "claro":"escuro", "limpo": "sujo", "verdadeiro": "falso", "rápido": "lento",
             "alegre": "triste", "novo": "velho", "limpo": "sujo", "cedo": "tarde"}

In [15]:
alias = antonimos

In [16]:
print(alias is antonimos)

True


In [17]:
alias['rápido']

'lento'

In [18]:
antonimos.items()

dict_items([('quente', 'frio'), ('alto', 'baixo'), ('certo', 'errado'), ('bonito', 'feio'), ('claro', 'escuro'), ('limpo', 'sujo'), ('verdadeiro', 'falso'), ('rápido', 'lento'), ('alegre', 'triste'), ('novo', 'velho'), ('cedo', 'tarde')])

In [20]:
antonimos.values()

dict_values(['frio', 'baixo', 'errado', 'feio', 'escuro', 'sujo', 'falso', 'lento', 'triste', 'velho', 'tarde'])

In [21]:
texto = "Ticking away the moments that make up a dull day Fritter and waste the hours in an offhand way. Kicking around on a piece of ground in your home town Waiting for someone or something to show you the way. Tired of lying in the sunshine staying home to watch the rain. You are young and life is long and there is time to kill today. And then one day you find ten years have got behind you. No one told you when to run, you missed the starting gun. So you run and you run to catch up with the sun but it's sinking Racing around to come up behind you again. The sun is the same in a relative way but you're older, Shorter of breath and one day closer to death. Every year is getting shorter never seem to find the time. Plans that either come to naught or half a page… "

In [22]:
dic_palavras = {}
for palavra in texto.split():
    dic_palavras[palavra] = 1 if palavra not in dic_palavras else dic_palavras[palavra] + 1
dic_palavras

{'Ticking': 1,
 'away': 1,
 'the': 9,
 'moments': 1,
 'that': 2,
 'make': 1,
 'up': 3,
 'a': 4,
 'dull': 1,
 'day': 3,
 'Fritter': 1,
 'and': 5,
 'waste': 1,
 'hours': 1,
 'in': 4,
 'an': 1,
 'offhand': 1,
 'way.': 2,
 'Kicking': 1,
 'around': 2,
 'on': 1,
 'piece': 1,
 'of': 3,
 'ground': 1,
 'your': 1,
 'home': 2,
 'town': 1,
 'Waiting': 1,
 'for': 1,
 'someone': 1,
 'or': 2,
 'something': 1,
 'to': 9,
 'show': 1,
 'you': 7,
 'Tired': 1,
 'lying': 1,
 'sunshine': 1,
 'staying': 1,
 'watch': 1,
 'rain.': 1,
 'You': 1,
 'are': 1,
 'young': 1,
 'life': 1,
 'is': 4,
 'long': 1,
 'there': 1,
 'time': 1,
 'kill': 1,
 'today.': 1,
 'And': 1,
 'then': 1,
 'one': 3,
 'find': 2,
 'ten': 1,
 'years': 1,
 'have': 1,
 'got': 1,
 'behind': 2,
 'you.': 1,
 'No': 1,
 'told': 1,
 'when': 1,
 'run,': 1,
 'missed': 1,
 'starting': 1,
 'gun.': 1,
 'So': 1,
 'run': 2,
 'catch': 1,
 'with': 1,
 'sun': 2,
 'but': 2,
 "it's": 1,
 'sinking': 1,
 'Racing': 1,
 'come': 2,
 'again.': 1,
 'The': 1,
 'same': 1,
 

In [23]:
#Gera uma lista de palvras com tamanho maior que 3

[p.upper() for p in dic_palavras if len(p) > 3]

['TICKING',
 'AWAY',
 'MOMENTS',
 'THAT',
 'MAKE',
 'DULL',
 'FRITTER',
 'WASTE',
 'HOURS',
 'OFFHAND',
 'WAY.',
 'KICKING',
 'AROUND',
 'PIECE',
 'GROUND',
 'YOUR',
 'HOME',
 'TOWN',
 'WAITING',
 'SOMEONE',
 'SOMETHING',
 'SHOW',
 'TIRED',
 'LYING',
 'SUNSHINE',
 'STAYING',
 'WATCH',
 'RAIN.',
 'YOUNG',
 'LIFE',
 'LONG',
 'THERE',
 'TIME',
 'KILL',
 'TODAY.',
 'THEN',
 'FIND',
 'YEARS',
 'HAVE',
 'BEHIND',
 'YOU.',
 'TOLD',
 'WHEN',
 'RUN,',
 'MISSED',
 'STARTING',
 'GUN.',
 'CATCH',
 'WITH',
 "IT'S",
 'SINKING',
 'RACING',
 'COME',
 'AGAIN.',
 'SAME',
 'RELATIVE',
 "YOU'RE",
 'OLDER,',
 'SHORTER',
 'BREATH',
 'CLOSER',
 'DEATH.',
 'EVERY',
 'YEAR',
 'GETTING',
 'SHORTER',
 'NEVER',
 'SEEM',
 'TIME.',
 'PLANS',
 'EITHER',
 'NAUGHT',
 'HALF',
 'PAGE…']

In [24]:
tam_p = {len(p) for p in dic_palavras}

In [25]:
tam_p

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [26]:
mapeamento = {val: index for index, val in enumerate(dic_palavras)}

In [27]:
mapeamento

{'Ticking': 0,
 'away': 1,
 'the': 2,
 'moments': 3,
 'that': 4,
 'make': 5,
 'up': 6,
 'a': 7,
 'dull': 8,
 'day': 9,
 'Fritter': 10,
 'and': 11,
 'waste': 12,
 'hours': 13,
 'in': 14,
 'an': 15,
 'offhand': 16,
 'way.': 17,
 'Kicking': 18,
 'around': 19,
 'on': 20,
 'piece': 21,
 'of': 22,
 'ground': 23,
 'your': 24,
 'home': 25,
 'town': 26,
 'Waiting': 27,
 'for': 28,
 'someone': 29,
 'or': 30,
 'something': 31,
 'to': 32,
 'show': 33,
 'you': 34,
 'Tired': 35,
 'lying': 36,
 'sunshine': 37,
 'staying': 38,
 'watch': 39,
 'rain.': 40,
 'You': 41,
 'are': 42,
 'young': 43,
 'life': 44,
 'is': 45,
 'long': 46,
 'there': 47,
 'time': 48,
 'kill': 49,
 'today.': 50,
 'And': 51,
 'then': 52,
 'one': 53,
 'find': 54,
 'ten': 55,
 'years': 56,
 'have': 57,
 'got': 58,
 'behind': 59,
 'you.': 60,
 'No': 61,
 'told': 62,
 'when': 63,
 'run,': 64,
 'missed': 65,
 'starting': 66,
 'gun.': 67,
 'So': 68,
 'run': 69,
 'catch': 70,
 'with': 71,
 'sun': 72,
 'but': 73,
 "it's": 74,
 'sinking': 75

# 4ª Aula - TETI - Funções

In [28]:
def f_soma(v1, v2):
    return v1 + v2

In [29]:
f_soma(100, 200)

300

In [35]:
def f_operacao(v1, v2, op):
    if op == '+':
        return v1 + v2
    elif op == '-':
        return v1 - v2
    elif op == '*':
        return v1 * v2
    elif op == '/':
        if v2 == 0:
            return 'Valor de v2 0 - inválido'
        return v1 / v2

In [36]:
f_operacao(123, 2, '/')

61.5

# 4ª Aula -  TETI - Numpy

In [38]:
import numpy as np

In [39]:
np.__version__

'1.23.5'

In [40]:
m1 = np.array([1, 2, 3, 4 , 5, 6])

In [41]:
m2 = np.array([7, 8, 9, 10 , 11, 12])

In [42]:
m1 + m2

array([ 8, 10, 12, 14, 16, 18])

In [43]:
m1 * m2

array([ 7, 16, 27, 40, 55, 72])

In [44]:
print([n*n for n in range(1000)])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 2656

In [47]:
%timeit [n*n for n in range(1000)]

120 µs ± 2.78 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
%timeit np.arange(1000)**2

4.96 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [49]:
m1 = np.random.rand(1000)
m2 = np.random.rand(1000)

In [50]:
m1

array([9.28669176e-01, 4.87487344e-01, 1.57483607e-01, 3.75086252e-01,
       5.86205225e-01, 2.94604127e-01, 3.72882184e-01, 9.38283039e-01,
       3.02844567e-01, 2.40258792e-01, 9.67722413e-01, 9.44898149e-02,
       5.86537147e-01, 8.67134108e-01, 3.89379122e-01, 2.54208089e-01,
       3.11593265e-01, 3.94012448e-01, 3.37688849e-01, 7.21399578e-01,
       7.37886210e-01, 3.31087991e-01, 5.41454939e-01, 6.48776790e-01,
       1.59303100e-01, 3.03844607e-01, 8.87579641e-01, 5.99809914e-01,
       3.54671546e-02, 9.42532025e-01, 7.13135731e-01, 1.32201924e-01,
       9.44838565e-01, 9.33681048e-01, 4.61099509e-01, 2.13836796e-02,
       7.86290620e-01, 1.23941760e-01, 8.08904484e-01, 7.64004952e-02,
       6.09534288e-01, 5.16023340e-01, 9.70628219e-01, 1.57257218e-01,
       9.38737691e-01, 9.58772681e-01, 1.29278851e-01, 5.01375572e-01,
       5.67707132e-01, 5.83128473e-01, 7.17044291e-01, 8.51960180e-01,
       3.14965965e-01, 9.34702544e-01, 3.50999692e-01, 3.06418622e-01,
      

In [51]:
def dot(m1, m2):
    s = 0
    for i in range(1000):
        s += m1[1] * m2[i]
    return s

In [56]:
%timeit dot(m1, m2)

597 µs ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [57]:
%timeit np.dot(m1, m2)

2.87 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [58]:
mat = np.random.rand(4, 5)

In [59]:
mat

array([[0.8653426 , 0.17071034, 0.87891865, 0.77359975, 0.90893033],
       [0.0875611 , 0.16054395, 0.44082771, 0.31762188, 0.36371976],
       [0.7189601 , 0.11086657, 0.80594249, 0.96837745, 0.68584477],
       [0.54889972, 0.90362193, 0.47594689, 0.38106146, 0.58114138]])

In [60]:
mat / 2

array([[0.4326713 , 0.08535517, 0.43945933, 0.38679987, 0.45446517],
       [0.04378055, 0.08027197, 0.22041385, 0.15881094, 0.18185988],
       [0.35948005, 0.05543328, 0.40297124, 0.48418872, 0.34292239],
       [0.27444986, 0.45181096, 0.23797344, 0.19053073, 0.29057069]])

In [61]:
mat *= 0.75

In [62]:
mat

array([[0.64900695, 0.12803275, 0.65918899, 0.58019981, 0.68169775],
       [0.06567082, 0.12040796, 0.33062078, 0.23821641, 0.27278982],
       [0.53922007, 0.08314993, 0.60445687, 0.72628309, 0.51438358],
       [0.41167479, 0.67771645, 0.35696017, 0.2857961 , 0.43585604]])

In [63]:
mat.shape

(4, 5)

In [66]:
mat.reshape(5, 4)

array([[0.64900695, 0.12803275, 0.65918899, 0.58019981],
       [0.68169775, 0.06567082, 0.12040796, 0.33062078],
       [0.23821641, 0.27278982, 0.53922007, 0.08314993],
       [0.60445687, 0.72628309, 0.51438358, 0.41167479],
       [0.67771645, 0.35696017, 0.2857961 , 0.43585604]])

In [67]:
mat.reshape(2, 10)

array([[0.64900695, 0.12803275, 0.65918899, 0.58019981, 0.68169775,
        0.06567082, 0.12040796, 0.33062078, 0.23821641, 0.27278982],
       [0.53922007, 0.08314993, 0.60445687, 0.72628309, 0.51438358,
        0.41167479, 0.67771645, 0.35696017, 0.2857961 , 0.43585604]])

In [68]:
mat.reshape(10, 2)

array([[0.64900695, 0.12803275],
       [0.65918899, 0.58019981],
       [0.68169775, 0.06567082],
       [0.12040796, 0.33062078],
       [0.23821641, 0.27278982],
       [0.53922007, 0.08314993],
       [0.60445687, 0.72628309],
       [0.51438358, 0.41167479],
       [0.67771645, 0.35696017],
       [0.2857961 , 0.43585604]])

In [69]:
mat.reshape(4, 5)

array([[0.64900695, 0.12803275, 0.65918899, 0.58019981, 0.68169775],
       [0.06567082, 0.12040796, 0.33062078, 0.23821641, 0.27278982],
       [0.53922007, 0.08314993, 0.60445687, 0.72628309, 0.51438358],
       [0.41167479, 0.67771645, 0.35696017, 0.2857961 , 0.43585604]])

In [70]:
mat.reshape(20,1)

array([[0.64900695],
       [0.12803275],
       [0.65918899],
       [0.58019981],
       [0.68169775],
       [0.06567082],
       [0.12040796],
       [0.33062078],
       [0.23821641],
       [0.27278982],
       [0.53922007],
       [0.08314993],
       [0.60445687],
       [0.72628309],
       [0.51438358],
       [0.41167479],
       [0.67771645],
       [0.35696017],
       [0.2857961 ],
       [0.43585604]])

In [71]:
mat.reshape(1,20)

array([[0.64900695, 0.12803275, 0.65918899, 0.58019981, 0.68169775,
        0.06567082, 0.12040796, 0.33062078, 0.23821641, 0.27278982,
        0.53922007, 0.08314993, 0.60445687, 0.72628309, 0.51438358,
        0.41167479, 0.67771645, 0.35696017, 0.2857961 , 0.43585604]])

In [73]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
np.empty((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.ones_like(mat)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
np.zeros_like(mat)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])